"""One-time seed data for the env_guide_* tables (migration _m030_env_guide).

Ported verbatim from the standalone 場域選型導覽.html reference tool
(無人自動化載具部署場域 x 三級設備建議, Sbjlink/Teltonika/iEi/Southco 原廠規格,
2026-07 逐條核對). Each constant is a JSON array-of-arrays string, parsed via
json.loads() by the migration and inserted once; after that, all further
changes go through the env_guide admin CRUD API, not this file.
"""

ENV_JSON = """
[
["A1","室內常溫搬運通道","一般物流場","0~50°C 即足夠","IP20~IP40 / IP20","無（僅 NCC/CE/FCC）","為此場域買 EN50155／E-Mark 等級是明顯 over-spec"],
["A2","高架密集料架區","一般物流場","0~50°C","IP20~IP40 / IP20","無","金屬料架造成 UWB 多路徑與 WiFi 死角，定位方案要先實測"],
["A3","裝卸月台與月台門","一般物流場","-20~60°C","IP54 以上 / IP66 以上","無","月台是半戶外卻常被當室內規劃，交換器接頭積水是最常見失效點"],
["A4","廠區與園區道路","一般物流場","-20~70°C 建議","IP54~IP65 / IP66 以上","上道路需 E-Mark","車體受曝面板溫度遠高於氣溫，無風扇機種在此最容易降頻"],
["B1","低溫加工／理貨區 10~15°C","冷鏈","-20~60°C","IP54 以上 / IP65 以上","食品接觸區需材質證明","清潔劑（次氯酸鈉／鹼性泡沫）腐蝕鋁擠與鍍鋅件，比水更傷"],
["B2","冷藏庫 0~5°C","冷鏈","-20~60°C 可過但需除濕","IP54＋密封 / IP65 以上","無","設備規格皆標 non-condensing，冷藏庫是 100% 會凝露的環境"],
["B3","冷凍庫 -18~-25°C","冷鏈","-40~75°C 必要","IP54＋密封＋加熱 / IP65","無","商規整機下限多為 -20°C 或 -10°C，直接不合格 — 本場域最大缺口"],
["B4","深凍／急凍庫 -30~-40°C","冷鏈","-40~75°C 且需實測低溫啟動","IP54＋加熱艙 / IP65","無","鋰電池 -25°C 僅剩 60~70% 容量，LFP 約 75~80%，續航需重算"],
["B5","溫層交界與庫門","冷鏈","-40~75°C","IP65＋密封 / IP66 以上","無","單趟進出可能造成鏡頭起霧、主控結露短路 — 冷鏈最常見失效點"],
["C1","半戶外（雨遮／廠棚下）","戶外","-20~65°C","IP54 以上 / IP66 以上","無","雨遮不等於免防水，側風雨與地面反濺仍會進水"],
["C2","全戶外（日曝／暴雨／颱風）","戶外","-40~75°C","IP65~IP67 / IP66~IP67","上道路需 E-Mark","台灣夏季戶外密閉機箱內部輕易超過 70°C，只看氣溫規劃必定失敗"],
["C3","港區／濱海／鹽霧","戶外","-40~75°C","IP66 以上 / IP66 以上","DNV GL 或 IACS 船級為加分","SUS304 對氯離子抗性不足，港區要 SUS316 以上；鋁擠會白化粉化"],
["D1","化工廠高溫製程區 40~60°C","化工／石化","-40~75°C（60°C 上限無餘裕）","IP54 以上 / IP65 以上","視分區","無風扇機種在 60°C 會降頻而非當機，效能悄悄掉一半最難察覺"],
["D2","氣體危險區 Zone 2 / Class I Div 2","化工／石化","-40~75°C","需 Ex 認證或 Ex p 正壓艙","ATEX Zone 2 Ex nA／Ex ec、ISA 12.12.01 C1D2","Zone 2 認證不可外推到 Zone 1；整車（含馬達／電池）都要認證"],
["D3","粉塵危險區 Zone 21/22 / Class II Div 2","化工／石化","-40~75°C","IP6X 必要（IP65 以上）","ATEX Ex tb／tc IIIC 或 C2D2","氣體用的 Ex nA 不等於粉塵用的 Ex t；IP30／IP40／IP54 機種全部不合格"],
["D4","腐蝕性化學品／酸鹼霧氣區","化工／石化","-20~65°C","IP67 / IP67","視分區","conformal coating 常被省略，但這是唯一能擋住酸鹼霧氣進入板面的手段"],
["D5","高壓沖洗／清潔區","化工／石化","-20~60°C","IP69K / IP69K","食品區 EHEDG／3-A 為加分","IP67 不等於能抗高壓熱水沖洗，IP69K 是完全不同的測試"],
["E1","半導體無塵室 Class 1~1000","延伸","0~50°C","IP20~IP40 / IP20","需微粒排放測試報告","無風扇機種的「外接風扇選配」在無塵室不可使用，會直接無法進場"],
["E2","食品廠沖洗區","延伸","-20~60°C","IP69K / IP69K","EHEDG／3-A／NSF 為加分","SUS304 遇含氯清潔劑會點蝕，高規需 SUS316L"],
["E3","製藥／GMP 潔淨區","延伸","0~50°C","IP65 以上 / IP65 以上","GMP 文件、材質證明","GMP 要的是文件與可清潔驗證，不是單看 IP 等級"],
["E4","醫院與長照場域","延伸","0~40°C","IP54 / IP54","IEC 60601-1-2 EMC 為加分","消毒劑（酒精／含氯）會讓塑膠件脆化，且醫療 EMC 門檻高於工業"],
["E5","地下停車場／隧道／地下倉","延伸","-20~60°C","IP54 / IP65","無","雙 SIM 跨電信備援在地下完全無用，這層冗餘要靠場域網路"],
["E6","鋼鐵／鑄造／熱處理","延伸","-40~75°C 且需實測","IP65 以上（導電粉塵）","EMS Level 3 以上","金屬粉塵導電，一旦進入機殼直接短路，IP54 完全不夠"],
["E7","水泥／礦場／砂石場","延伸","-40~75°C","IP65 以上 / IP66 以上","部分區域需 Zone 22","散熱鰭片積塵在數週內就會顯著降低散熱效率，規格書看不出來"],
["E8","農業溫室／畜牧場","延伸","-20~60°C","IP65 以上 / IP66 以上","部分沼氣區需 Zone 2","氨氣會腐蝕接點鍍層與 PCB 銅箔，一般工業級壽命會大幅縮短"],
["E9","汙水處理廠","延伸","-40~75°C","IP66 以上 / IP66 以上","消化槽區需 ATEX Zone 1/2","H2S 對銀與銅腐蝕極強，且消化槽周邊是沼氣防爆區，常被漏列"],
["E10","垃圾處理／資源回收場","延伸","-40~75°C","IP65 以上 / IP66 以上","部分需 Zone 2/22","同時具備粉塵／腐蝕／沼氣三重風險，單一防護策略不足"],
["E11","軌道與大眾運輸","延伸","-40~85°C","IP54 以上 / IP66 以上","EN50155、EN45545-2、ITxPT","EN45545-2 是防火與煙毒性，與 EN50155 是兩件事，常被混為一談"],
["E12","變電站／電力設施","延伸","-40~85°C","IP54 / IP54 以上","IEC 61850-3、IEEE 1613","變電站突波等級遠高於一般工廠，一般工業交換器會反覆重開機"],
["全部","跨場域通用（三層）","通用","—","—","—","以下三層與場域無關，但每個專案都必須處理"]
]
"""

REC_JSON = """
[
["A1","通訊層 行動網路","車輛端 車內電控箱","Teltonika RUT200","Teltonika RUT956","Teltonika RUTM54（5G）","室內常溫多以場域 WiFi 為主路徑，行動網路僅作備援，因此此層常被降規","若場域 WiFi 覆蓋良好，RUT901 即足夠，不必為 GPS 多付 RUT956 的價差"],
["A1","匯集層 車載交換器","車輛端 車內電控箱","一般工業交換器（RJ45＋防鬆脫護套）","Sbjlink RPT-M1810GP-T-X2 IP40","Sbjlink RPT-M2010G-T-X2（網管全 Gigabit）","此場域最容易 over-spec：平整地面低速載具的振動可能不需要 M12 等級","建議 PoC 階段裝加速規實測振動頻譜，再決定是否值得 M12 的線束成本"],
["A1","運算層 主控","車輛端 車內電控箱","iEi uIBX-250-BW 或 WAFER 板卡","iEi DRPC-240-TGL-U（ESDQ AMR 預驗證）","iEi TANK-XM813（Core Ultra＋NPU）","整合風險是此層的主要成本，而非硬體單價；有 ESDQ 背書者可省下大量整合工時","DRPC-240 選配 PoE af 模組後可直接供電 4 路感測器，對簡化車型可省下一台交換器"],
["A1","定位層","車輛端","主控 USB GPS（僅室外段）","SLAM 為主（缺口，需另案）","SLAM＋UWB 混合","室內 GNSS 完全失效；業界以 SLAM 為主，特徵單調區補反光板","FMC650 在純室內場域價值有限，若無室外段可考慮改用 FMC130 或省略"],
["A1","致動層 貨艙鎖","車輛端 貨艙門板","通用 12V 物流櫃鎖閂（僅驗證機構）","Southco R4-EM＋微動開關回授（S=6）","Southco R4-EM＋EA 控制器","微動開關回授應列必選；無回授的鎖具會產生無法排除的營運爭議","低價品可用於 PoC 驗證機構配合尺寸，但量產不建議"],
["A1","環境端網路","環境端 機櫃／機房","Sbjlink EL-1005 系列 或 Teltonika TSW 非網管","Sbjlink ecoLink 或 Teltonika TSW202（網管 PoE+）","Sbjlink L2/L3＋2.5G/10G 系列","場站側是三層架構的匯聚點，網管與 PoE 預算是主要判斷","能放環境端就放環境端：維護容易、成本低、單點故障不影響載具運行"],
["A2","通訊層 行動網路","車輛端 車內電控箱","Teltonika RUT200","Teltonika RUT956＋外接天線","Teltonika RUTM54＋外接天線","金屬車體與金屬料架雙重遮蔽，外接天線在此不是選配而是必要","天線接地與安裝位置顯著影響連線品質，需向原廠索取配件線一併詢價"],
["A2","定位層","車輛端與環境端","反光板三角定位","SLAM（LiDAR）","UWB＋SLAM 融合","金屬環境會造成 UWB 多路徑干擾，業界在此更常用反光板或 SLAM","先實測再決定；金屬料架密集區 UWB 精度可能不如規格書，這項測試成本低但價值高"],
["A2","環境端網路 無線AP","環境端 天花／樑柱","一般商規 AP","Teltonika TAP200 或 UniFi AP","支援無縫漫遊的企業級 AP","移動載具最怕漫遊斷線，一般 AP 的漫遊切換時間可能超過控制訊號容許值","必須確認 AP 是否支援 802.11r/k/v 無縫漫遊，這比 AP 的頻寬規格更重要"],
["A3","匯集層 車載交換器","車輛端 車內電控箱","Sbjlink RPT-M1810GP-T-X2 IP40","Sbjlink RPT-M1810GP-2G-I54-T-X2 IP54","Sbjlink RPT-M2010P／M2010G IP54 版（網管）","月台是半戶外，IP54 是此場域的實務底線","IP54 是否含 M12 接頭鎖固後的整體等級，或僅機殼本體，需向原廠確認"],
["A3","運算層 主控","車輛端 車內電控箱","iEi DRPC-124-EHL","iEi DRPC-240-TGL-U（裝入密封電控箱）","iEi TANK-XM813（35W 版）","整機均標示 non-condensing；月台溫差凝露是實質風險，電控箱密封＋乾燥劑是業界作法","DRPC-124 上限 50°C，在夏季月台密閉艙內幾乎必定超標，不建議"],
["A3","環境端網路","環境端 戶外桿件／牆面","Sbjlink RPT-1905HP-OD（5 埠戶外）","Sbjlink RPT-1912HP-2F-OD（12 埠戶外，6KV 防雷）","Sbjlink RPT-2012GP-4F-X4（NEMA TS2 網管）","月台側設備應直接選原生戶外機，而非室內機加防水箱","戶外機多為 90~240VAC 直入，需與電氣工程一併規劃，不可事後補"],
["A3","致動層 貨艙鎖","車輛端 貨艙門板","Southco R4-EM 標準型（C=1）","Southco R4-EM 密封接頭 C=3（Molex MX150）＋微動開關","Southco R4-EM 不鏽鋼版 M=B＋EA 控制器","接頭是鎖具最常見的失效點；防水型連接器版本在半戶外是必要","線束走向需避免積水，這是機構設計階段就要處理的事"],
["A4","通訊層 行動網路","車輛端 車內電控箱","Teltonika RUT901","Teltonika RUT956＋外接天線","Teltonika RUTM54（5G 遠端接管）","園區道路是 4G 覆蓋較穩的場域，雙 SIM 跨電信備援在此最有價值","若載具會上一般道路，E-Mark 由加分變必要，且須依無人載具科技創新實驗條例申請場域試驗"],
["A4","匯集層 車載交換器","車輛端 車內電控箱","Sbjlink RPT-M1810GP IP40＋遮陽","Sbjlink RPT-M1810GP-2G-I54-T-X2 IP54","Sbjlink RPT-M2010P／M2010G IP54（網管）或 Moxa TN-4500A","-40~75°C 的 75°C 上限可涵蓋日曝密閉艙，這是 Sbjlink 在此場域的關鍵優勢","車體受曝面板溫度遠高於氣溫；需在預定安裝位置放溫度記錄器連續記錄一個工作日"],
["A4","運算層 主控","車輛端 主運算艙","iEi DRPC-240（需實測降頻）","iEi TANK-XM813 35W 版","Winmate WNAI-E600（E-Mark＋9~36V＋ACC）","主控上限 60°C 在日曝密閉艙內餘裕極小，高端機種的價值在此體現","需做高溫效能實測：將主控置於實測到的最高溫環境下跑滿載，確認降頻後效能是否仍可接受"],
["A4","環境端網路","環境端 戶外桿件","Teltonika OTD140（IP55 戶外路由器）","Sbjlink RPT-1912HP-2F-OD＋RPT-2012GP-4F-X4","Sbjlink FLC-2528G-4XF-I-T（10G 光纖幹線）","路側點位以光纖幹線＋戶外 PoE 交換器為業界標準架構","防雷是戶外設備的第一課，6KV 突波保護是底線；接地設計比設備規格更決定壽命"],
["A4","遙測層 LoRa","環境端 戶外桿件","無（改用有線）","Sbjlink LGT-3C28-W1 戶外型 LoRa","LoRa＋光纖雙路","車格佔用偵測、閘門狀態、環境感測用 LoRa 可大幅減少佈線成本","台灣 LoRa 頻段合規（AS923）與防雷擊突波規格需一併確認"],
["B1","匯集層 車載交換器","車輛端 車內電控箱","Sbjlink RPT-M1810GP IP40","Sbjlink RPT-M1810GP-2G-I54-T-X2 IP54","Sbjlink RPT-M2010G IP54 網管","溫度不是問題，清潔劑霧氣與高濕才是；IP54 為底線","清潔劑腐蝕鋁擠與鍍鋅件比水更傷；需確認外殼材質與是否可 conformal coating"],
["B1","運算層 主控","車輛端 車內電控箱","iEi DRPC-240（密封電控箱）","iEi DRPC-240＋密封箱＋乾燥劑","iEi TANK-XM813＋正壓微加壓電控箱","正壓電控箱是食品與冷鏈的業界作法，可同時阻擋濕氣與清潔劑霧氣","正壓所需氣源與濾芯維護需納入維運 SOP"],
["B1","維運終端 HMI","環境端 站台","一般工業面板電腦","iEi SHIELD-215（不鏽鋼 -30~55°C）","iEi INOX-F15C-ULT3（SUS304 IP69K）","食品相關區域的終端一律不鏽鋼，這是稽核會查的項目","SUS304 遇含氯清潔劑會點蝕；高規需 SUS316L，需向原廠確認是否有 316 版本"],
["B1","冷鏈監控","貨艙內部","無","Teltonika TSH202／EYE 藍牙溫濕度感測器","FMC650＋Carrier 冷凍機 RS232 介接","冷鏈稽核需要溫度履歷，藍牙感測器免佈線是主流作法","量測精度與校正證書是冷鏈稽核的必要文件，需向原廠索取"],
["B2","匯集層 車載交換器","車輛端 車內電控箱","不建議入門方案","Sbjlink RPT-M1810GP-2G-I54-T-X2 IP54","Sbjlink RPT-M2010G IP54 網管＋冗餘電源","-40~75°C 的寬溫範圍在此有充分餘裕；IP54＋密封是重點","規格書標示 non-condensing，但冷藏庫進出是 100% 會凝露 — 需以密封＋乾燥劑或微加熱處理"],
["B2","運算層 主控","車輛端 密封電控箱","不建議入門方案","iEi DRPC-240＋密封箱＋微加熱","iEi TANK-XM813＋恆溫電控箱","0~5°C 對主控本身不是問題，凝露才是；業界以密封艙加微加熱處理","主控與電池分開供電或加小型 UPS，避免瞬斷造成重開、停在通道中央阻礙作業"],
["B2","定位層","車輛端","無","SLAM（需鏡頭防霧）","UWB＋SLAM 融合","LiDAR 與相機鏡頭在冷藏庫進出時會起霧，光學件加熱是業界作法","鏡頭起霧會讓 SLAM 直接失效，這比低溫對電子件的影響更立即"],
["B2","致動層 貨艙鎖","車輛端 貨艙門板","通用 12V 鎖閂（不建議）","Southco R4-EM 密封接頭 C=3＋微動開關","Southco R4-EM 不鏽鋼版＋EA 控制器","R4-EM 的 -40~80°C 與 IP56 在冷鏈是少數直接合規的選項","低溫下潤滑脂會變稠影響動作，需向原廠確認是否需低溫規格潤滑脂"],
["B3","通訊層 行動網路","車輛端 密封電控箱","無","Teltonika RUT956（-40~75°C，裝入密封箱）","Teltonika RUT956＋恆溫加熱艙","溫度規格通過，但 IP30 在此完全不夠，一律裝入密封箱","IP30 加密封箱是可行路徑，但箱內凝露需以乾燥劑或微加熱處理，且需留意天線引出線的密封"],
["B3","匯集層 車載交換器","車輛端 車內電控箱","無","Sbjlink RPT-M1810GP-2G-I54-T-X2（-40~75°C IP54）","Sbjlink RPT-M2010G IP54 網管＋雙冗餘電源","Sbjlink M12 系列的 -40°C 下限，是本清單中唯一能直接進冷凍庫的網路設備","需向原廠索取 -25°C 環境下的低溫啟動實測數據；規格下限與實際冷啟動能力是兩件事"],
["B3","運算層 主控","車輛端 恆溫加熱艙","無","無合規標準品 — 需恆溫加熱艙","iEi DRPC-240 或 TANK-XM813＋恆溫加熱艙","主控是冷凍庫的最大缺口：商規整機下限多為 -20°C 或 -10°C，直接不合格，業界一律用恆溫艙","關鍵缺口：需向 iEi 確認是否有 -40°C 寬溫機種；若無，則加熱艙的耗電必須納入整車電力預算"],
["B3","維運終端 HMI","環境端 庫內操作站／車載終端","無","iEi SHIELD-215（-30~55°C、10~28V、含隔離 CANBUS）","不鏽鋼＋加熱型面板電腦","SHIELD-215 的 -30°C 下限是本清單少數可直接進冷凍庫的整機；具 CANBUS＋寬電壓，也可作車載終端","低溫下觸控與 LCD 反應會變慢，需實測；部分機種需加熱型面板"],
["B3","電源層 電池","車輛端 恆溫電池艙","無","LFP 電池＋加熱艙","LFP＋恆溫艙＋快充策略","鋰電池在 -20°C 僅剩 60~70% 容量，LFP 約 75~80%，冷鏈載具續航必須重算","低溫下鋰電池充電會析鋰，需先加熱到安全溫度才能充電"],
["B4","匯集層 車載交換器","車輛端 車內電控箱","無","Sbjlink RPT-M1810GP-2G-I54-T-X2（-40°C 下限剛好）","Sbjlink M12 系列＋恆溫艙","-40°C 是規格下限，在 -40°C 環境運行沒有餘裕，業界仍會加恆溫艙","規格下限等於環境溫度時，應向原廠索取降額曲線並考慮加熱艙"],
["B4","運算層 主控","車輛端 恆溫加熱艙","無","無合規標準品","恆溫加熱艙＋車規 -40°C 機種","深凍庫的電子件一律進恆溫艙，這已不是選型問題而是機構設計問題","恆溫艙的加熱功率與整車電力預算的衝突，是此場域的核心設計取捨"],
["B4","感知層 感測器","車輛端 車外","無","LiDAR＋鏡頭週期加熱","加熱型 LiDAR 罩＋除霜循環","感測器結霜是深凍庫最常見的失效模式，週期加熱是業界標準作法","LiDAR 廠商是否提供低溫版本與加熱罩，這需在感測器選型階段就確認"],
["B5","全層（系統設計）","車輛端","無","密封＋乾燥劑＋進出緩衝停留","恆溫艙＋加熱除濕循環＋光學件加熱","業界作法是在溫層邊界減速停留，讓設備有時間過渡，避免凝露形成","這是冷鏈自動化最常見失效點，且無法用單一設備選型解決，必須是系統設計"],
["C1","匯集層 車載交換器","車輛端 車內電控箱","Sbjlink RPT-M1810GP IP40","Sbjlink RPT-M1810GP-2G-I54-T-X2 IP54","Sbjlink RPT-M2010P／M2010G IP54 網管","雨遮不等於免防水，側風雨與地面反濺仍會進水，IP54 為底線","線束走向需避免積水；轉角需應力釋放，避免長期振動造成斷芯"],
["C1","環境端網路","環境端 桿件／牆面","Sbjlink RPT-1905HP-OD","Sbjlink RPT-1912HP-2F-OD（6KV 防雷）","Sbjlink RPT-2012GP-4F-X4（NEMA TS2）","半戶外的環境端設備仍應選原生戶外機，成本差異不大但壽命差很多","-30~60°C 的上限 60°C 在夏季戶外機箱內可能不足，需加遮陽罩或通風設計"],
["C2","通訊層 行動網路","車輛端／環境端 桿件","Teltonika RUT901（車內電控箱）","RUT956（車內）＋OTD140（環境端 IP55）","RUTM54（車內）＋原生 IP67 戶外機（需另尋）","Teltonika 車載機種一律 IP30，必須裝入電控箱；環境端則有 OTD140 原生戶外機","OTD140 為 IP55，若為颱風直接吹襲的點位可能不足，需評估 IP66/67 機種"],
["C2","匯集層 車載交換器","車輛端 車內電控箱","不建議入門方案","Sbjlink RPT-M1810GP-2G-I54-T-X2 IP54＋遮陽","Sbjlink RPT-M2010G IP54 網管＋隔熱艙","-40~75°C 的 75°C 上限是全戶外的關鍵，但仍需遮陽避免直接日曝","台灣夏季戶外密閉機箱內部輕易超過 70°C，只看氣溫規劃必定失敗"],
["C2","運算層 主控","車輛端 隔熱主運算艙","不建議入門方案","iEi TANK-XM813 35W 版＋主動散熱","Winmate WNAI-E600 或 SINTRONES 車規機種","主控上限 60°C 在全戶外是最大風險，業界在此改用車規機種而非商規整機","無風扇不等於免散熱設計；高溫時處理器會降頻而非當機，需在高溫下實測效能"],
["C2","環境端網路","環境端 戶外桿件","Sbjlink RPT-1905HP-OD","Sbjlink RPT-1912HP-2F-OD＋光纖幹線","Sbjlink FLC-2528G-4XF-I-T（10G 光纖）＋防雷器","全戶外一律以光纖作幹線；銅纜跨戶外段落是雷擊損壞的主因","防雷 6KV 是底線且需獨立接地；光纖幹線可從根本上避免雷擊沿線傳導"],
["C3","匯集層 車載交換器","車輛端 車內密封電控箱","不建議入門方案","Sbjlink RPT-M1810GP-2G-I54-T-X2＋conformal coating","Sbjlink RPT-2012GP-4F-DNV-X3（DNV GL 船級）","船級認證（DNV GL）是鹽害場域最直接的規格證明，業界在港區會直接要求","需確認是否提供 conformal coating，以及外殼是否為 SUS316（SUS304 對氯離子抗性不足）"],
["C3","環境端網路","環境端 戶外機櫃","Sbjlink RPT-1912HP-2F-OD","Sbjlink RPT-1008G-DNV-X3（船級）","Sbjlink RPT-2012GP-4F-DNV-X3（船級 網管 PoE+）","Sbjlink 的 Marine DNV GL 系列在此是明顯優勢，一般工業機種在港區壽命會顯著縮短","鹽霧測試小時數（ISO 9227 中性鹽霧）是可量化的比較基準，應列入詢價表"],
["C3","致動層 鎖具","車輛端 貨艙門板","不建議入門方案","Southco R4-EM 不鏽鋼版 M=B＋密封接頭 C=3","Southco R4-EM SUS316 版（需確認是否有）","鹽害場域的鎖具材質不可妥協，鍍鎳鋼在港區會鏽蝕","原廠型錄僅標示不鏽鋼為 passivated，未指明 304 或 316，必須確認等級並索取材質證明"],
["D1","匯集層 車載交換器","車輛端 車內電控箱","不建議入門方案","Sbjlink RPT-M1810GP（-40~75°C）","Sbjlink RPT-M2010G 網管＋隔熱艙","-40~75°C 的 75°C 上限在此是關鍵；一般商規交換器上限 60°C 直接不足","環境 60°C 加上機箱內自身發熱，內部可能接近 75°C，需實測而非推估"],
["D1","運算層 主控","車輛端 隔熱主運算艙","無","iEi DRPC-240＋外接風扇 SF-DRPC-240","車規 -40~70/85°C 機種（Winmate／SINTRONES）","iEi 機種上限 60°C 在 40~60°C 環境無餘裕；業界在此改用車規寬溫機種或將主控外移","關鍵：需向 iEi 索取 60°C 環境下的持續效能實測 — 降頻後效能是否仍可支撐 SLAM 加視覺辨識，這是本場域最需要驗證的一項"],
["D1","電源與防護","車輛端","無","隔熱艙＋主動散熱","隔熱艙＋液冷或熱管導出","高溫區的業界作法是把發熱源與熱源隔開，而非一味提升設備溫度規格","DC-DC 轉換損耗會以熱的形式累積在密閉艙內，這部分常被漏算"],
["D2","環境端網路","環境端 危險區機箱","Sbjlink RPT-1005GP-X4（C1D2/ATEX 非網管）","Sbjlink RPT-2010G-2F-X4（ATEX Zone 2 Ex nA nC IIC T4 Gc＋C1D2＋UL61010）","Advantech EKI-5728I（ATEX＋C1D2＋IECEx 三重認證）","原生 ATEX 機種是唯一正確做法；IECEx 認證涵蓋範圍比僅有 ATEX 者更廣","Zone 2 認證不可外推到 Zone 1；且寬溫版本（-40~75°C 選配）是否影響防爆認證，必須向原廠確認"],
["D2","匯集層 車載交換器","車輛端 Ex p 正壓艙","無","無合規標準品 — 需 Ex p 正壓吹淨艙","已認證的防爆載具（ANYbotics ANYmal X 等級）","車載交換器與主控均無 ATEX 認證；業界作法是整車走 Ex p 正壓吹淨，或直接採購已認證載具","關鍵：整車（含馬達、電池、驅動器）都要認證，不是只有網通設備 — 這是本場域最大的成本與時程風險"],
["D2","運算層 主控","車輛端 Ex p 正壓艙","無","iEi DRPC-240 裝入 Ex p 正壓艙","已認證的防爆載具","正壓吹淨（Ex p）是讓商規設備進入危險區的標準工程手段","正壓艙需氣源、壓力監測與失壓聯鎖，這一整套的成本可能超過設備本身"],
["D3","環境端網路","環境端 Ex t IIIC 外箱","無","Sbjlink RPT-2010G-2F-X4 裝入 Ex t IIIC 外箱","原生 Ex tb／tc IIIC 認證機種（需另尋）","重要：ATEX Zone 2 Ex nA（氣體）不等於 Zone 21/22 的 Ex t（粉塵），兩者不可互換","Sbjlink ATEX 機種為 IP30，在粉塵區完全不合格；粉塵區需 IP6X，一律裝入 Ex t IIIC 認證外箱"],
["D3","匯集層 車載交換器","車輛端 Ex t IIIC 外箱","無","Sbjlink RPT-M1810GP IP54 裝入 Ex t IIIC 外箱","原生 Ex t IIIC 認證機種","IP54 在粉塵防爆區仍不合格；需 IP6X，且外箱表面溫度需低於粉塵最低著火溫度的三分之二","粉塵區的關鍵不只是防塵，還有表面溫度限制；高功耗設備在此可能因表面溫度超標而不可用"],
["D3","運算層 主控","車輛端 Ex t IIIC 外箱","無","無合規方案 — 需另案評估","已認證的防爆載具","粉塵防爆的主控幾乎沒有標準品；業界改用已認證載具或大幅簡化車上運算","建議將運算移至環境端（邊緣伺服器），車上僅留最小控制，這可大幅降低防爆認證範圍"],
["D4","匯集層 車載交換器","車輛端 密封電控箱","無","Sbjlink RPT-M1810GP IP54＋conformal coating","Sbjlink RPT-2010G-2F-X4（ATEX）＋SUS316 外箱","conformal coating 是唯一能擋住酸鹼霧氣進入板面的手段，常被省略但不可省","需向原廠確認是否提供 conformal coating 服務，以及塗層等級與厚度"],
["D4","致動層 鎖具","車輛端 貨艙門板","無","Southco R4-EM 不鏽鋼版 M=B","Southco R4-EM SUS316（需確認）＋全灌膠接頭","酸鹼區的接頭必須灌膠，這是最常見的失效點","SUS304 在含氯環境會點蝕，需確認是否有 SUS316 版本"],
["D5","維運終端 HMI","環境端 沖洗區","無","iEi INOX-F15C-ULT3（SUS304 IP69K）","原生 SUS316L IP69K 機種","IP67 不等於能抗高壓熱水沖洗；IP69K 是完全不同的測試（80°C／100bar）","INOX-F15C-ULT3 平台世代較舊，需確認 EOL 與是否有新世代 SUS316 版本"],
["D5","匯集層與運算層","車輛端 IP69K 外箱","無","商規設備裝入 IP69K 外箱","原生 IP69K 機種（需另尋）","本清單三家均無 IP69K 車載網通與運算設備，需以外箱處理","IP69K 外箱的接頭與線束出線是最難的部分，需專業外箱供應商"],
["E1","匯集層 車載交換器","車輛端 車內電控箱","一般工業交換器（RJ45）","Sbjlink RPT-M2010G（全 Gigabit 網管，無風扇）","Moxa TN-4500A（無風扇＋conformal coating）","無塵室的關鍵不是溫度或 IP，而是微粒排放與 ESD；一切風扇設計都禁止","交換器本身多為無風扇，但需向原廠索取微粒排放測試報告 — 這是機台進場的必要文件"],
["E1","運算層 主控","車輛端 車內電控箱","iEi DRPC-124-EHL（無風扇）","iEi DRPC-240（無風扇，不可加外接風扇）","iEi TANK-XM813 35W 版（無風扇，不可加外接風扇）","iEi 2026 COMPUTEX 展出 TANK-XM813＋iVEC 的晶圓搬運 AMR 安全防護方案，顯示對此領域持續投入","關鍵：DRPC-240 與 TANK-XM813 的外接風扇選配在無塵室不可使用，必須確認純無風扇狀態下的持續效能與溫度"],
["E1","定位層","車輛端與環境端","二維碼導引","SLAM＋反光板","UWB＋SLAM＋AMHS 整合","半導體廠的 AMHS 整合（SECS/GEM）比定位方案本身更決定專案成敗","SECS/GEM 整合屬軟體範疇，但會反向決定主控的運算與介面需求，應在主控定案前釐清"],
["E2","維運終端 HMI","環境端 沖洗區","無","iEi SHIELD-215（不鏽鋼六面防護）","iEi INOX-F15C-ULT3（SUS304 IP69K）","食品廠一律不鏽鋼；EHEDG／3-A／NSF 認證是加分但客戶常會要求","SUS304 遇含氯清潔劑會點蝕，高規需 SUS316L；圓角無縫焊接與排水設計是稽核重點"],
["E2","匯集層與運算層","車輛端 IP69K 外箱","無","商規設備裝入不鏽鋼 IP69K 外箱","原生 IP69K 機種","本清單無 IP69K 車載設備，需以不鏽鋼外箱處理","外箱需符合衛生設計（無死角、可排水），這與一般防護箱是不同的規格"],
["E5","通訊層 行動網路","車輛端 車內電控箱","無（地下無電信訊號）","場域 WiFi 為主＋RUT956 作地面段備援","場域 WiFi＋漏纜＋5G 小基站","關鍵：Teltonika 雙 SIM 跨電信備援在地下完全無用，這一層冗餘必須靠場域網路","必須佈建場域 WiFi 或漏纜，且需支援無縫漫遊 — 這是本場域的必要投資而非選配"],
["E5","定位層","車輛端與環境端","二維碼或磁條導引","SLAM（LiDAR）","UWB＋SLAM 融合","GNSS 完全失效；FMC650 在此無定位價值（仍可作 CAN 擷取）","隧道與長通道特徵單調，SLAM 易漂移，需補反光板或 UWB"],
["E5","環境端網路","環境端 天花／壁面","Sbjlink EL-1005 系列","Sbjlink RPT-1912HP-2F-OD（防潮滴水）","Sbjlink 網管系列＋光纖幹線","地下環境高濕滴水，環境端設備應選 IP65 以上","車輛廢氣與高濕會加速接點腐蝕，conformal coating 有價值"],
["E6","匯集層 車載交換器","車輛端 隔熱電控箱","無","Sbjlink RPT-M1810GP IP54＋隔熱艙","Sbjlink RPT-M2010G＋光纖上行＋隔熱艙","金屬粉塵導電，一旦進入機殼會直接短路；IP54 不夠，需 IP65 以上，且銅纜應改光纖","強電磁環境中銅纜會拾取干擾；Sbjlink HNT-1401G-1F-T-X6EL 微型媒體轉換器可在車上做銅轉光"],
["E6","運算層 主控","車輛端 隔熱主運算艙","無","無合規標準品","車規 -40~85°C 機種＋隔熱艙","輻射熱區的環境溫度可遠超 70°C，商規整機在此無方案，業界改用車規機種加隔熱","建議將主控移出輻射熱區，或改為環境端邊緣運算，車上僅留最小控制"],
["E7","匯集層 車載交換器","車輛端 車內電控箱","Sbjlink RPT-M1810GP IP40","Sbjlink RPT-M1810GP-2G-I54-T-X2 IP54","Sbjlink M12 系列 IP54＋IP65 外箱","重粉塵環境：散熱鰭片積塵在數週內就會顯著降低散熱效率，這是規格書看不出來的衰減","選無鰭片外露設計或完全密封機種；定期清潔納入維運 SOP 並估算工時成本"],
["E7","環境端網路","環境端 戶外桿件","Sbjlink RPT-1905HP-OD","Sbjlink RPT-1912HP-2F-OD","Sbjlink RPT-2012GP-4F-X4＋光纖幹線","重粉塵加強振動，環境端一律選戶外密閉機種","部分區域可能屬 Zone 22 粉塵防爆區，需先確認場域分區圖"],
["E8","匯集層 車載交換器","車輛端 密封電控箱","Sbjlink RPT-M1810GP IP40","Sbjlink RPT-M1810GP-2G-I54-T-X2＋conformal coating","Sbjlink M12 IP54＋正壓電控箱","氨氣會腐蝕接點鍍層與 PCB 銅箔，conformal coating 在此不是選配","一般工業級設備在氨氣環境壽命會大幅縮短，需向原廠確認是否有耐氨氣測試數據"],
["E8","環境端網路","環境端 桿件","Sbjlink RPT-1905HP-OD","Sbjlink RPT-1912HP-2F-OD＋LGT-3C28-W1（LoRa）","Sbjlink 網管＋LoRa＋光纖","溫室與畜牧場範圍大但資料量小，LoRa 遙測比佈設有線網路划算","部分沼氣區可能屬 Zone 2，需確認場域分區"],
["E9","環境端網路","環境端 危險區機箱","Sbjlink RPT-1005GP-X4（C1D2/ATEX）","Sbjlink RPT-2010G-2F-X4（ATEX Zone 2）＋conformal coating","Advantech EKI-5728I（IECEx）或 Sbjlink DNV 系列","Sbjlink 官網有汙水處理廠解決方案案例；消化槽周邊屬沼氣防爆區，常被漏列","H2S 對銀與銅腐蝕極強，conformal coating 必要；且需確認 ATEX 分區是否涵蓋消化槽區"],
["E9","匯集層 車載交換器","車輛端 密封電控箱","無","Sbjlink RPT-M1810GP IP54＋conformal coating","Sbjlink M12＋Ex p 正壓艙（進入消化槽區）","非防爆區可用一般 IP54 車載機；進入消化槽區則需 Ex p","先取得場域防爆分區圖，再決定載具的行走路線是否需要進入分區 — 這可大幅降低成本"],
["E11","匯集層 車載交換器","車輛端 車內電控箱","無","Sbjlink RPT-M1810GP-T-X2（EN50155＋EN45545-2＋IEC61373）","Moxa TN-4500A（EN50155＋conformal coating）或 Sbjlink RPT-M2010P 網管","EN45545-2 是防火與煙毒性，與 EN50155 是兩件事，軌道應用兩者都要","Sbjlink 規格書標示 ITxPT／E-Mark 為 Pending，需索取現行有效證書 — 這在軌道專案是投標文件"],
["E11","運算層 主控","車輛端 主運算艙","無","iEi 現有清單無 EN50155 認證機種","IBASE 或 SINTRONES 的 EN50155 車載電腦","iEi 現有清單無 EN50155 機種，軌道應用需改選原生軌道機種","若後續需與大眾運輸系統介接，ITxPT 是關鍵標準；iEi 清單目前無 ITxPT 機種"],
["E12","環境端網路","環境端 變電站機櫃","Sbjlink RPT-1010G-2F-I-T-X3（IEC 61850-3 非網管）","Sbjlink RPT-2012G-4F-I-T-X3（IEC 61850-3 網管）","Sbjlink FLC-2528G-4XF-I-T（IEC 61850-3＋10G 上行，模組化）","變電站的電磁突波等級遠高於一般工廠，一般工業交換器會反覆重開機，必須用原生 IEC 61850-3 機種","IEEE 1613 是否一併具備需確認；不要用一般工業級加裝突波保護替代，這在變電站是無效的"],
["E12","匯集層 車載交換器","車輛端 車內電控箱","無","Sbjlink RPT-M1810GP＋光纖上行（HNT-1401G）","Sbjlink M12＋全光纖架構","強電磁環境中銅纜跨區段會拾取干擾，光纖是唯一可靠選擇","車上做銅轉光可用 Sbjlink HNT-1401G-1F-T-X6EL 微型媒體轉換器，體積與重量表現佳"],
["全部","安全層 功能安全","車輛端 硬線迴路","急停按鈕（前後各一）","急停＋安全雷射掃描器＋安全繼電器","同左＋防撞緩衝條＋馬達驅動器 STO","三家供應商均無此產品線；業界慣例為硬線迴路或安全 PLC，不可依賴一般網路","危險區需確認安全元件本身是否具 ATEX；冷鏈需確認掃描器的低溫與結霜可靠度。建議另案評估 Pilz／Sick／Keyence／Omron，且必須在機構設計初期納入"],
["全部","管理端 裝置管理","雲端","無（人工現場維護）","Teltonika RMS（Networks 設備）","RMS＋自建派車系統 API 整合","車隊超過十台後，能不能遠端排除故障直接決定維運人力成本","RMS 只管 Teltonika Networks 設備；iEi 主控與 Sbjlink 交換器需另有管理方案，這個落差常被忽略"],
["全部","電源與防護","車輛端","直接取車電","DC-DC 模組＋突波保護＋點火控制（ACC）","同左＋主控與通訊小型 UPS 或超級電容","Sbjlink M12 系列原生支援 24~48VDC 雙冗餘（另有 72~110VDC 版本）；iEi 機種為 12~28VDC，48V 車電需加 DC-DC","重要修正：Sbjlink 並非只有 24V 升壓，而是有 LV（24~48V）與 HV（72~110V）兩種版本 — 48V 車電不需額外 DC-DC，iEi 則必須加"]
]
"""

LINKS_JSON = """
[
["RPT-M2010P","https://www.sbjlink.com/products_view.php?id=203","Sbjlink 原廠產品頁"],
["RPT-M2010G","https://www.sbjlink.com/products_view.php?id=204","Sbjlink 原廠產品頁"],
["RPT-M1810GP","https://www.sbjlink.com/products_view.php?id=188","Sbjlink 產品頁＋規格書"],
["RPT-M1010GP","https://www.sbjlink.com/products_view.php?id=188","Sbjlink 產品頁＋規格書"],
["RPT-M1810P","https://www.sbjlink.com/products_view.php?id=187","Sbjlink 原廠產品頁"],
["RPT-M1812P","https://www.sbjlink.com/products_view.php?id=70","Sbjlink 原廠產品頁"],
["RPT-M1012","https://www.sbjlink.com/products_view.php?id=69","Sbjlink 原廠產品頁"],
["RPT-2010G-2F-X4","https://www.sbjlink.com/products_view.php?id=170","Sbjlink ATEX 產品頁＋規格書"],
["RPT-1005GP-X4","https://www.sbjlink.com/products_view.php?id=172","Sbjlink ATEX 產品頁"],
["RPT-1010G-2F-X4","https://www.sbjlink.com/products_view.php?id=171","Sbjlink ATEX 產品頁"],
["RPT-2012G-4F-I-T-X3","https://www.sbjlink.com/products_view.php?id=199","Sbjlink IEC 61850-3 產品頁"],
["RPT-1010G-2F-I-T-X3","https://www.sbjlink.com/products_view.php?id=198","Sbjlink IEC 61850-3 產品頁"],
["FLC-2528G","https://www.sbjlink.com/products_view.php?id=281","Sbjlink 10G 模組化產品頁"],
["RPT-2012GP-4F-DNV","https://www.sbjlink.com/products_view.php?id=117","Sbjlink DNV 船級產品頁"],
["RPT-1008G-DNV","https://www.sbjlink.com/products_view.php?id=115","Sbjlink DNV 船級產品頁"],
["RPT-2012GP-4F-X4","https://www.sbjlink.com/products_view.php?id=169","Sbjlink NEMA TS2 產品頁"],
["RPT-1912HP","https://www.sbjlink.com/products_view.php?id=305","Sbjlink 戶外 PoE 產品頁＋規格書"],
["RPT-1905HP","https://www.sbjlink.com/products_view.php?id=304","Sbjlink 戶外 PoE 產品頁"],
["RPT-1919HP","https://www.sbjlink.com/products_view.php?id=306","Sbjlink 戶外 PoE 產品頁"],
["HNT-1401G","https://www.sbjlink.com/products_view.php?id=297","Sbjlink 媒體轉換器產品頁"],
["LGT-3628","https://www.sbjlink.com/products_view.php?id=268","Sbjlink 室內 LoRa 產品頁"],
["LGT-3C28","https://www.sbjlink.com/products_view.php?id=269","Sbjlink 戶外 LoRa 產品頁"],
["EL-1005","https://www.sbjlink.com/products.php?scat=36","Sbjlink Automation 類別"],
["ecoLink","https://www.sbjlink.com/products.php?scat=49","Sbjlink ecoLink 類別"],
["RUT200","https://store.innotrust.com.tw/product/detail/2613641/teltonika-rut200-compact-industrial-4g-router","英菲達 RUT200（NT$4,949）"],
["RUT901","https://store.innotrust.com.tw/product/detail/2613636/teltonika-rut901-industrial-4g-lte-router","英菲達 RUT901（NT$6,569）"],
["RUT956","https://www.teltonika-networks.com/products/routers/rut956","Teltonika RUT956 原廠頁"],
["RUTM54","https://store.innotrust.com.tw/product/detail/2613651/teltonika-rutm54-industrial-5g-wifi6-router","英菲達 RUTM54（已售完）"],
["OTD140","https://www.teltonika-networks.com/products/routers/otd140","Teltonika OTD140 原廠頁"],
["TSW202","https://www.teltonika-networks.com/newsroom/teltonikas-tsw202-managed-switch-for-poe-management","Teltonika TSW202 原廠新聞"],
["TAP200","https://www.teltonika-networks.com/products","Teltonika 全產品線"],
["FMC650","https://wiki.teltonika-gps.com/view/FMC650_Carrier","Teltonika FMC650 Carrier Wiki"],
["RMS","https://store.innotrust.com.tw/category/203413","英菲達 Teltonika 專頁"],
["DRPC-240","https://www.ieiworld.com/en/product/model.php?II=871","iEi DRPC-240 原廠頁"],
["DRPC-124","https://www.ieiworld.com/en/product/model.php?II=965","iEi DRPC-124 原廠頁"],
["TANK-XM813","https://www.ieiworld.com/en/product/model.php?II=1099","iEi TANK-XM813 原廠頁"],
["TANK-XM810","https://www.ieiworld.com/en/product/model_pdf.php?II=872","iEi TANK-XM810 規格"],
["SHIELD-215","https://www.ieiworld.com/en/product/model.php?II=1094","iEi SHIELD-215 原廠頁"],
["INOX-F15C","https://www.ieiworld.com/en/product/model.php?II=588","iEi INOX-F15C IP69K 原廠頁"],
["R4-EM","https://media.southco.com/media/static/Literature/r4-em-od.en.pdf","Southco R4-EM 型錄（含訂購碼）"],
["H3-EM","https://southco.com/en_us_int/latches/electronic-access-locking-solutions/electronic-cam-latches/h3-em-electronic-locking-swinghandle","Southco H3-EM 系列頁"],
["UniFi","https://store.innotrust.com.tw/category/82849","英菲達 UniFi Door Access"],
["EKI-5728I","https://www.advantech.com/products/1-2mlk0j/eki-5728i/mod_aec25fc0-171c-44f5-82b3-8e0ad895ada0","Advantech EKI-5728I 原廠頁"],
["TN-4500A","https://www.moxa.com/en/products/industrial-network-infrastructure/ethernet-switches/en-50155-switches/tn-4500a-series","Moxa TN-4500A 系列頁"]
]
"""
